name: Django CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

    - name: Build Docker image
      run: docker build -t django-app .

    - name: Stop old container
      run: docker stop django-container || true

    - name: Remove old container
      run: docker rm django-container || true

    - name: Run new container
      run: docker run -d --name django-container -p 5000:5000 django-app
